app:
  image: jod
  ports:
    - "80:3000"
  links:
    - mysql
mysql:
  image: mysql:5.7
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: jod
    MYSQL_DATABASE: jod
  volumes:
    - ./sql/dump.sql:/docker-entrypoint-initdb.d/schema.sql:ro
