SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Account;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Account(
  accountId INT AUTO_INCREMENT,
  active TINYINT NOT NULL DEFAULT 1,
  userId INT NOT NULL,
  accountName VARCHAR(200) NOT NULL,
  PRIMARY KEY(accountId),
  FOREIGN KEY(userId)
    REFERENCES `User`(userId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE = INNODB DEFAULT CHARSET=utf8;