SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Budget;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Budget(
  BudgetId INT AUTO_INCREMENT,
  AccountId INT NOT NULL,
  BudgetName VARCHAR(100) NOT NULL UNIQUE,
  Created DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY(BudgetId),
  FOREIGN KEY(AccountId)
    REFERENCES `Account`(AccountId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE = INNODB DEFAULT CHARSET=utf8;