SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Image;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Image(
  imageId INT AUTO_INCREMENT,
  description VARCHAR(500),
  s3Url VARCHAR(500) NOT NULL,
  PRIMARY KEY(imageId)
) ENGINE = INNODB DEFAULT CHARSET=utf8;