SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Image;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Image(
  imageId INT AUTO_INCREMENT,
  `key` VARCHAR(100) NOT NULL UNIQUE,
  s3Url VARCHAR(500) NOT NULL UNIQUE,
  description VARCHAR(500),
  PRIMARY KEY(imageId)
) ENGINE = INNODB DEFAULT CHARSET=utf8;