SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Tag;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Tag(
  TagId INT AUTO_INCREMENT,
  TagName VARCHAR(50) NOT NULL,
  TagColor VARCHAR(6) NOT NULL,
  PRIMARY KEY(TagId)
) ENGINE = INNODB DEFAULT CHARSET=utf8;