SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS TagGroupMap;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE TagGroupMap(
  tagGroupId INT,
  tagId INT,
  PRIMARY KEY(tagGroupId, tagId),
  FOREIGN KEY(tagGroupId)
    REFERENCES TagGroup(tagGroupId)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY(tagId)
    REFERENCES Tag(tagId)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET=utf8;