SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS TagMap;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE TagMap(
  budgetItemId INT NOT NULL,
  tagId INT NOT NULL,
  PRIMARY KEY(BudgetItemId, TagId),
  FOREIGN KEY(BudgetItemId)
    REFERENCES BudgetItem(BudgetItemId)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY(TagId)
    REFERENCES Tag(TagId)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET=utf8;