SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Tags;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Tags(
  BudgetItemId INT NOT NULL,
  TagId INT NOT NULL,
  PRIMARY KEY(BudgetItemId, TagId),
  FOREIGN KEY(BudgetItemId)
    REFERENCES BudgetItem(BudgetItemId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  FOREIGN KEY(TagId)
    REFERENCES Tag(TagId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE = INNODB DEFAULT CHARSET=utf8;