SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `User`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `User`(
  userId INT AUTO_INCREMENT,
  active TINYINT NOT NULL DEFAULT 1,
  email VARCHAR(300) NOT NULL,
  username VARCHAR(100) NOT NULL,
  PRIMARY KEY(userId),
  INDEX(Email)
) ENGINE = INNODB DEFAULT CHARSET=utf8;