SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `User`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `User`(
  UserId INT AUTO_INCREMENT,
  Email VARCHAR(300) NOT NULL,
  Username VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  PRIMARY KEY(UserId),
  INDEX(Email)
) ENGINE = INNODB DEFAULT CHARSET=utf8;